#!/bin/sh
# This is a shell archive (produced by GNU sharutils 4.15.2).
# To extract the files from this archive, save it to some FILE, remove
# everything before the '#!/bin/sh' line above, then type 'sh FILE'.
#
lock_dir=_sh06749
# Made on 2018-10-20 14:53 EDT by <joseph@msi>.
# Source directory was '/home/joseph/Desktop/COP4620 Compilers/Project2'.
#
# Existing files will *not* be overwritten, unless '-c' is specified.
#
# This shar contains:
# length mode       name
# ------ ---------- ------------------------------------------
#    475 -rw-r--r-- doc.txt
#     27 -rwxrwxrwx p2
#   2177 -rw-rw-r-- parse.py
#   3977 -rw-rw-r-- tools.py
#   2625 -rw-r--r-- grammar
#   3297 -rw-r--r-- p1.py
#   1021 -rw-rw-r-- p2.py
#   1237 -rw-rw-r-- testfiles
#    379 -rw-r--r-- typescript
#   1895 -rw-r--r-- first_sets
#     63 -rw-rw-r-- makefile
#
MD5SUM=${MD5SUM-md5sum}
f=`${MD5SUM} --version | egrep '^md5sum .*(core|text)utils'`
test -n "${f}" && md5check=true || md5check=false
${md5check} || \
  echo 'Note: not verifying md5sums.  Consider installing GNU coreutils.'
if test "X$1" = "X-c"
then keep_file=''
else keep_file=true
fi
echo=echo
save_IFS="${IFS}"
IFS="${IFS}:"
gettext_dir=
locale_dir=
set_echo=false

for dir in $PATH
do
  if test -f $dir/gettext \
     && ($dir/gettext --version >/dev/null 2>&1)
  then
    case `$dir/gettext --version 2>&1 | sed 1q` in
      *GNU*) gettext_dir=$dir
      set_echo=true
      break ;;
    esac
  fi
done

if ${set_echo}
then
  set_echo=false
  for dir in $PATH
  do
    if test -f $dir/shar \
       && ($dir/shar --print-text-domain-dir >/dev/null 2>&1)
    then
      locale_dir=`$dir/shar --print-text-domain-dir`
      set_echo=true
      break
    fi
  done

  if ${set_echo}
  then
    TEXTDOMAINDIR=$locale_dir
    export TEXTDOMAINDIR
    TEXTDOMAIN=sharutils
    export TEXTDOMAIN
    echo="$gettext_dir/gettext -s"
  fi
fi
IFS="$save_IFS"
if (echo "testing\c"; echo 1,2,3) | grep c >/dev/null
then if (echo -n test; echo 1,2,3) | grep n >/dev/null
     then shar_n= shar_c='
'
     else shar_n=-n shar_c= ; fi
else shar_n= shar_c='\c' ; fi
f=shar-touch.$$
st1=200112312359.59
st2=123123592001.59
st2tr=123123592001.5 # old SysV 14-char limit
st3=1231235901

if   touch -am -t ${st1} ${f} >/dev/null 2>&1 && \
     test ! -f ${st1} && test -f ${f}; then
  shar_touch='touch -am -t $1$2$3$4$5$6.$7 "$8"'

elif touch -am ${st2} ${f} >/dev/null 2>&1 && \
     test ! -f ${st2} && test ! -f ${st2tr} && test -f ${f}; then
  shar_touch='touch -am $3$4$5$6$1$2.$7 "$8"'

elif touch -am ${st3} ${f} >/dev/null 2>&1 && \
     test ! -f ${st3} && test -f ${f}; then
  shar_touch='touch -am $3$4$5$6$2 "$8"'

else
  shar_touch=:
  echo
  ${echo} 'WARNING: not restoring timestamps.  Consider getting and
installing GNU '\''touch'\'', distributed in GNU coreutils...'
  echo
fi
rm -f ${st1} ${st2} ${st2tr} ${st3} ${f}
#
if test ! -d ${lock_dir} ; then :
else ${echo} "lock directory ${lock_dir} exists"
     exit 1
fi
if mkdir ${lock_dir}
then ${echo} "x - created lock directory ${lock_dir}."
else ${echo} "x - failed to create lock directory ${lock_dir}."
     exit 1
fi
# ============= doc.txt ==============
if test -n "${keep_file}" && test -f 'doc.txt'
then
${echo} "x - SKIPPING doc.txt (file already exists)"

else
${echo} "x - extracting doc.txt (text)"
  sed 's/^X//' << 'SHAR_EOF' > 'doc.txt' &&
This program performs the functions of a parser for a C- language.
X
Components:
X	p1.py - scanner from Project 1 that obtains a token stack
X	p2.py - driver code for Project 2 that calls p1 and other necessary functions
X	parse.py - program that does the actual parsing given the context of the problem
X	tools.py - contains functions to load in the grammar and first sets and compute the follow sets
X
Input: source program to parse, grammar, first sets
Output: ACCEPT or REJECT
SHAR_EOF
  (set 20 18 10 20 14 47 33 'doc.txt'
   eval "${shar_touch}") && \
  chmod 0644 'doc.txt'
if test $? -ne 0
then ${echo} "restore of doc.txt failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'doc.txt': 'MD5 check failed'
       ) << \SHAR_EOF
5d5bbbe9738e691a70ccfdf8f5ac6465  doc.txt
SHAR_EOF

else
test `LC_ALL=C wc -c < 'doc.txt'` -ne 475 && \
  ${echo} "restoration warning:  size of 'doc.txt' is not 475"
  fi
fi
# ============= p2 ==============
if test -n "${keep_file}" && test -f 'p2'
then
${echo} "x - SKIPPING p2 (file already exists)"

else
${echo} "x - extracting p2 (text)"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 p2
;(R$O8FEN+V)A<V@*<'ET:&]N('`R+G!Y("0Q
`
end
SHAR_EOF
  (set 20 18 10 19 16 44 14 'p2'
   eval "${shar_touch}") && \
  chmod 0777 'p2'
if test $? -ne 0
then ${echo} "restore of p2 failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'p2': 'MD5 check failed'
       ) << \SHAR_EOF
19ee2104fcf0fde92c569628fcc9a5d3  p2
SHAR_EOF

else
test `LC_ALL=C wc -c < 'p2'` -ne 27 && \
  ${echo} "restoration warning:  size of 'p2' is not 27"
  fi
fi
# ============= parse.py ==============
if test -n "${keep_file}" && test -f 'parse.py'
then
${echo} "x - SKIPPING parse.py (file already exists)"

else
${echo} "x - extracting parse.py (text)"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 parse.py
M(B(B"E1H:7,@9G5N8W1I;VX@=7-E<R!,3"@Q*2!P87)S:6YG('1E8VAN:7%U
M97,@=&\@9&5T97)M:6YE('=H971H97(@86X@:6YP=70@<')O9W)A;0II<R!A
M8V-E<'1A8FQE('<N<BYT(&$@9VEV96X@9W)A;6UA<BX*26YP=70Z('-E92!P
M87)A;7,*3W5T<'5T.B!!0T-%4%0@;W(@4D5*14-4"B(B(@ID968@<&%R<V4H
M=&]K96YS+"!G<F%M;6%R+"!F:7)S=%]S971S+"!F;VQL;W=?<V5T<RP@=&5R
M;6EN86QS+"!N;VYT97)M:6YA;',L('-T87)T*3H*("`@(&5P<VEL;VX@/2`B
M0"(*("`@('-T86-K(#T@6R<D)RP@<W1A<G1="B`@("!C=7)R96YT+"!T;VME
M;B`](%MX+G!O<"@I(&9O<B!X(&EN(%MS=&%C:RP@=&]K96YS75T*("`@('=H
M:6QE(&-U<G)E;G0@(3T@)R0G(&]R('1O:V5N("$]("<D)SH*("`@("`@("!W
M:&EL92!C=7)R96YT(#T]('1O:V5N.B!C=7)R96YT+"!T;VME;B`](%L@>"YP
M;W`H*2!F;W(@>"!I;B!;<W1A8VLL('1O:V5N<UU="B`@("`@("`@:68@8W5R
M<F5N="!N;W0@:6X@;F]N=&5R;6EN86QS.B!R971U<FX@1F%L<V4@(R!214I%
M0U0@+2!U;F5X<&5C=&5D('1O:V5N"B`@("`@("`@;F5X=%]R=6QE(#T@5')U
M92`C(&9L86<@9F]R(&)R96%K:6YG('1H92!R=6QE(&QO;W`*("`@("`@("!F
M;W(@<G5L92!I;B!G<F%M;6%R6V-U<G)E;G1=.B`C(&9I;F0@=&AE(')U;&4@
M=&AA="!G96YE<F%T97,@8W5R<F5N="!T;VME;@H@("`@("`@("`@("!I9B!N
M97AT7W)U;&4Z"B`@("`@("`@("`@("`@("!F;W(@<')O9'5C=&EO;B!I;B!R
M=6QE.B`*("`@("`@("`@("`@("`@("`@("!I9B!P<F]D=6-T:6]N(&EN(&YO
M;G1E<FUI;F%L<SH*("`@("`@("`@("`@("`@("`@("`@("`@:68@=&]K96X@
M:6X@9FER<W1?<V5T<UMP<F]D=6-T:6]N73H*("`@("`@("`@("`@("`@("`@
M("`@("`@("`@(&-U<G)E;G0@/2!P<F]D=6-T:6]N"B`@("`@("`@("`@("`@
M("`@("`@("`@("`@("!I9B!L96XH<G5L92D@/B`Q.B!S=&%C:RYE>'1E;F0H
M<F5V97)S960H<G5L95LQ.ETI*0H@("`@("`@("`@("`@("`@("`@("`@("`@
M("`@;F5X=%]R=6QE(#T@1F%L<V4*("`@("`@("`@("`@("`@("`@("`@("`@
M96QI9B!E<'-I;&]N(&EN(&9I<G-T7W-E='-;<')O9'5C=&EO;ETZ(&-O;G1I
M;G5E(",@=')Y(&YE>'0@<')O9'5C=&EO;@H@("`@("`@("`@("`@("`@("`@
M("`@("!E;'-E.B`C('1R>2!N97AT(')U;&4L(%)%2D5#5"!I9B!N;R!M;W)E
M('1O('1R>0H@("`@("`@("`@("`@("`@("`@("`@("`@("`@:68@<G5L92`]
M/2!G<F%M;6%R6V-U<G)E;G1=6RTQ73H@<F5T=7)N($9A;'-E"B`@("`@("`@
M("`@("`@("`@("`@96QI9B!P<F]D=6-T:6]N(#T](&5P<VEL;VXZ"B`@("`@
M("`@("`@("`@("`@("`@("`@(&EF('1O:V5N(&EN(&9O;&QO=U]S971S6V-U
M<G)E;G1=.@H@("`@("`@("`@("`@("`@("`@("`@("`@("`@8W5R<F5N="`]
M('-T86-K+G!O<"@I"B`@("`@("`@("`@("`@("`@("`@("`@("`@("!N97AT
M7W)U;&4@/2!&86QS90H@("`@("`@("`@("`@("`@("`@("`@("!E;'-E.B!R
M971U<FX@1F%L<V4@(R!214I%0U0@+2!T;VME;B!N;W0@:6X@9F]L;&]W<R!O
M9B!C=7)R96YT"B`@("`@("`@("`@("`@("`@("`@96QI9B!P<F]D=6-T:6]N
M(&EN('1E<FUI;F%L<SH*("`@("`@("`@("`@("`@("`@("`@("`@:68@=&]K
M96X@/3T@<')O9'5C=&EO;CH*("`@("`@("`@("`@("`@("`@("`@("`@("`@
M(&-U<G)E;G0@/2!P<F]D=6-T:6]N"B`@("`@("`@("`@("`@("`@("`@("`@
M("`@("!I9B!L96XH<G5L92D@/B`Q.B!S=&%C:RYE>'1E;F0H<F5V97)S960H
M<G5L95LQ.ETI*0H@("`@("`@("`@("`@("`@("`@("`@("`@("`@;F5X=%]R
M=6QE(#T@1F%L<V4*("`@("`@("`@("`@("`@("`@("`@("`@96QS93H@(R!T
M<GD@;F5X="!R=6QE+"!214I%0U0@:68@;F\@;6]R92!T;R!T<GD*("`@("`@
M("`@("`@("`@("`@("`@("`@("`@(&EF(')U;&4@/3T@9W)A;6UA<EMC=7)R
M96YT75LM,5TZ(')E='5R;B!&86QS90H@("`@("`@("`@("`@("`@("`@(&5L
M<V4Z(')E='5R;B!&86QS92`C(%)%2D5#5"`M('-H;W5L9&XG="!R96%C:"!H
M97)E"B`@("`@("`@("`@("`@("`@("`@8G)E86L@(R!B<F5A:R!P<F]D=6-T
M:6]N(&QO;W`*("`@(')E='5R;B!4<G5E(&EF(&-U<G)E;G0@/3T@=&]K96X@
1/3T@)R0G(&5L<V4@1F%L<V5R
`
end
SHAR_EOF
  (set 20 18 10 19 16 31 10 'parse.py'
   eval "${shar_touch}") && \
  chmod 0664 'parse.py'
if test $? -ne 0
then ${echo} "restore of parse.py failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'parse.py': 'MD5 check failed'
       ) << \SHAR_EOF
5a9d18301a186ca15cfbf941349362a1  parse.py
SHAR_EOF

else
test `LC_ALL=C wc -c < 'parse.py'` -ne 2177 && \
  ${echo} "restoration warning:  size of 'parse.py' is not 2177"
  fi
fi
# ============= tools.py ==============
if test -n "${keep_file}" && test -f 'tools.py'
then
${echo} "x - SKIPPING tools.py (file already exists)"

else
${echo} "x - extracting tools.py (text)"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 tools.py
M9G)O;2!S>7,@:6UP;W)T(&5X:70*9G)O;2!R92!I;7!O<G0@9FEN9&%L;`H*
M(B(B"E1H:7,@9G5N8W1I;VX@<F5A9',@82!F:6QE(&-O;G1A:6YI;F<@82!F
M;W)M871T960@9W)A;6UA<B!A;F0@;&]A9',@:70@:6YT;R!A(&1I8W0N"DEN
M<'5T.B`@("`@("!3("T^(&$@4R!C('P@8B!\($`@("`*3W5T<'5T.B`@("`@
M(&=R86UM87);4UT@/2!;6R=A)RPG4R<L)V,G72Q;)V(G72Q;)T`G75T@(`HB
M(B(*9&5F(&QO861?9W)A;6UA<BAF:6QE;F%M92DZ"B`@("!G<F%M;6%R(#T@
M>WT*("`@('1E<FUI;F%L<R`](%M=("`@(`H@("`@=')Y.@H@("`@("`@('=I
M=&@@;W!E;BAF:6QE;F%M92P@)W(G*2!A<R!G9CH*("`@("`@("`@("`@9F]R
M(&DL(&QI;F4@:6X@96YU;65R871E*&=F*3H*("`@("`@("`@("`@("`@(&QI
M;F4@/2!L:6YE+G-P;&ET*"<M/B<I"B`@("`@("`@("`@("`@("!I9B!I(#T]
M(#`Z('-T87)T(#T@;&EN95LP72YS=')I<"@I"B`@("`@("`@("`@("`@("!G
M<F%M;6%R6VQI;F5;,%TN<W1R:7`H*5T@/2!;9FEN9&%L;"AR)UQ3*R<L(')U
M;&4I(&9O<B!R=6QE(&EN(&QI;F5;,5TN<W!L:70H)WPG*5T*("`@(&5X8V5P
M=#H*("`@("`@("!P<FEN="`B17)R;W(@;&]A9&EN9R!G<F%M;6%R+B(*("`@
M("`@("!E>&ET*"D*"B`@("!N;VYT97)M:6YA;',@/2!G<F%M;6%R+FME>7,H
M*0H@("`@"B`@("!F;W(@<G5L97-E="!I;B!G<F%M;6%R+G9A;'5E<R@I.@H@
M("`@("`@(&9O<B!R=6QE(&EN(')U;&5S970Z"B`@("`@("`@("`@(&9O<B!E
M;&5M96YT(&EN(')U;&4Z"B`@("`@("`@("`@("`@("!I9B!E;&5M96YT(&YO
M="!I;B!N;VYT97)M:6YA;',@86YD(&5L96UE;G0@;F]T(&EN('1E<FUI;F%L
M<SH*("`@("`@("`@("`@("`@("`@("!T97)M:6YA;',N87!P96YD*&5L96UE
M;G0I"B`@("`*("`@(')E='5R;B!G<F%M;6%R+"!T97)M:6YA;',L(&YO;G1E
M<FUI;F%L<RP@<W1A<G0*"B(B(@I4:&ES(&9U;F-T:6]N(')E861S(&$@9FEL
M92!C;VYT86EN:6YG(&9O<FUA='1E9"!F:7)S="!S971S(&%N9"!L;V%D<R!T
M:&5M(&EN=&\@82!D:6-T+@HB(B(*9&5F(&QO861?9FER<W1S*&9I;&5N86UE
M*3H*("`@(&9I<G-T7W-E=',@/2![?0H@("`@=')Y.@H@("`@("`@('=I=&@@
M;W!E;B@B9FER<W1?<V5T<R(L("=R)RD@87,@9G,Z"B`@("`@("`@("`@(&9O
M<B!L:6YE(&EN(&9S.@H@("`@("`@("`@("`@("`@;&EN92`](&QI;F4N<W!L
M:70H)RI[)RD*("`@("`@("`@("`@("`@(&9I<G-T7W-E='-;;&EN95LP72YS
M=')I<"@I72`](&QI;F5;,5TN<W1R:7`H*2YS<&QI="@I"B`@("!E>&-E<'0Z
M"B`@("`@("`@<')I;G0@(D5R<F]R(&QO861I;F<@9FER<W0@<V5T<RXB"B`@
M("`@("`@97AI="@I"B`@("!R971U<FX@9FER<W1?<V5T<PH*(B(B"E1H:7,@
M9G5N8W1I;VX@9FEN9',@=&AE(&9O;&QO=R!S971S(&]F(&$@9W)A;6UA<BX*
M26YP=70Z(&=R86UM87(@9&EC="P@=&5R;6EN86QS("8@;F]N=&5R;6EN86QS
M('-E=',O;&ES=',L(&9I<G-T('-E=',@9&EC="P@86YD(`IT:&4@<W1A<G0@
M<')O9'5C=&EO;B!O9B!G<F%M;6%R+@I/=71P=70Z(&9O;&QO=R!S971S(&1I
M8W0N"B(B(@ID968@9FEN9%]F;VQL;W=S*&=R86UM87(L(&YO;G1E<FUI;F%L
M<RP@=&5R;6EN86QS+"!F:7)S=%]S971S+"!S=&%R="DZ"B`@("!F;VQL;W=?
M<V5T<R`]('M]"B`@("!E<'-I;&]N(#T@(D`B"B`@("!F;W(@;G0@:6X@;F]N
M=&5R;6EN86QS.B!F;VQL;W=?<V5T<UMN=%T@/2!S970H*0H@("`@9F]L;&]W
M7W-E='-;<W1A<G1=+F%D9"@G)"<I"B`@("!C:&%N9V5S(#T@5')U90H@("`@
M=VAI;&4@*&-H86YG97,I.@H@("`@("`@(&-H86YG97,@/2!&86QS90H@("`@
M("`@(&9O<B!N="!I;B!N;VYT97)M:6YA;',Z"B`@("`@("`@("`@(&9O<B!R
M=6QE(&EN(&=R86UM87);;G1=.@H@("`@("`@("`@("`@("`@(R!A9&0@9&ER
M96-T(&9O;&QO=W,*("`@("`@("`@("`@("`@(&9O<B!I+"!P<F]D=6-T:6]N
M(&EN(&5N=6UE<F%T92AR=6QE*3H@(R!I=&5R871E('1H<F]U9V@@="`F(&YT
M(&EN(')U;&4*("`@("`@("`@("`@("`@("`@("!I9B!P<F]D=6-T:6]N(&EN
M(&YO;G1E<FUI;F%L<SH*("`@("`@("`@("`@("`@("`@("`@("`@9F]R('DL
M('!R;V1?869T97)?:2!I;B!E;G5M97)A=&4H<G5L95MI*S$Z72DZ"B`@("`@
M("`@("`@("`@("`@("`@("`@("`@("`C(&EF('1E<FUI;F%L+"!A9&0@=&\@
M9F]L;&]W<RP@=&AE;B!B<F5A:PH@("`@("`@("`@("`@("`@("`@("`@("`@
M("`@:68@<')O9%]A9G1E<E]I(&EN('1E<FUI;F%L<SH*("`@("`@("`@("`@
M("`@("`@("`@("`@("`@("`@("!I9B!P<F]D7V%F=&5R7VD@;F]T(&EN(&9O
M;&QO=U]S971S6W!R;V1U8W1I;VY=.@H@("`@("`@("`@("`@("`@("`@("`@
M("`@("`@("`@("`@("!F;VQL;W=?<V5T<UMP<F]D=6-T:6]N72YA9&0H<')O
M9%]A9G1E<E]I*0H@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@
M("!C:&%N9V5S(#T@5')U90H@("`@("`@("`@("`@("`@("`@("`@("`@("`@
M("`@(&)R96%K"B`@("`@("`@("`@("`@("`@("`@("`@("`@("`C(&%D9"![
M9FER<W1S?2`M('ME<'-I;&]N?2!I9B!I="!C86X@9V\@87=A>2P@=&AE;B!C
M;VYT:6YU92`*("`@("`@("`@("`@("`@("`@("`@("`@("`@(&EF(&9I<G-T
M7W-E='-;<')O9%]A9G1E<E]I75LM,5T@/3T@97!S:6QO;CH*("`@("`@("`@
M("`@("`@("`@("`@("`@("`@("`@("!F;W(@:B!I;B!F:7)S=%]S971S6W!R
M;V1?869T97)?:5U;.BTQ73H*("`@("`@("`@("`@("`@("`@("`@("`@("`@
M("`@("`@("`@:68@:B!N;W0@:6X@9F]L;&]W7W-E='-;<')O9'5C=&EO;ETZ
M"B`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("!F;VQL
M;W=?<V5T<UMP<F]D=6-T:6]N72YA9&0H:BD*("`@("`@("`@("`@("`@("`@
M("`@("`@("`@("`@("`@("`@("`@(&-H86YG97,@/2!4<G5E"B`@("`@("`@
M("`@("`@("`@("`@("`@("`@("`C(&EF(&YE>'0@<')O9'5C=&EO;B!C86YT
M(&=O(&%W87DL(&IU<W0@861D(&ET<R!F:7)S=',L('1H96X@8G)E86L*("`@
M("`@("`@("`@("`@("`@("`@("`@("`@(&5L<V4Z"B`@("`@("`@("`@("`@
M("`@("`@("`@("`@("`@("`@9F]R(&P@:6X@9FER<W1?<V5T<UMP<F]D7V%F
M=&5R7VE=.@H@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@("!I
M9B!L(&YO="!I;B!F;VQL;W=?<V5T<UMP<F]D=6-T:6]N73H*("`@("`@("`@
M("`@("`@("`@("`@("`@("`@("`@("`@("`@("`@(&9O;&QO=U]S971S6W!R
M;V1U8W1I;VY=+F%D9"AL*0H@("`@("`@("`@("`@("`@("`@("`@("`@("`@
M("`@("`@("`@("`@8VAA;F=E<R`](%1R=64*("`@("`@("`@("`@("`@("`@
M("`@("`@("`@("`@("!B<F5A:PH@("`@("`@("`@("`@("`@(R!A9&0@:6YD
M:7)E8W0@9F]L;&]W<PH@("`@("`@("`@("`@("`@9F]R('@@:6X@<F5V97)S
M960H<G5L92DZ"B`@("`@("`@("`@("`@("`@("`@:68@>"!I;B!N;VYT97)M
M:6YA;',Z"B`@("`@("`@("`@("`@("`@("`@("`@(&9O<B!W(&EN(&9O;&QO
M=U]S971S6VYT73H*("`@("`@("`@("`@("`@("`@("`@("`@("`@(&EF('<@
M;F]T(&EN(&9O;&QO=U]S971S6WA=.@H@("`@("`@("`@("`@("`@("`@("`@
M("`@("`@("`@(&9O;&QO=U]S971S6WA=+F%D9"AW*0H@("`@("`@("`@("`@
M("`@("`@("`@("`@("`@("`@(&-H86YG97,@/2!4<G5E"B`@("`@("`@("`@
M("`@("`@("`@("`@(&EF(&9I<G-T7W-E='-;>%U;+3%=(#T](&5P<VEL;VXZ
M(&-O;G1I;G5E"B`@("`@("`@("`@("`@("`@("`@("`@(&5L<V4Z(&)R96%K
M"B`@("`@("`@("`@("`@("`@("`@96QS93H@8G)E86L*("`@("-F;W(@:V5Y
M+"!I=&5M(&EN(&9O;&QO=U]S971S+FET96US*"DZ('!R:6YT(")+15DZ('LZ
M,C5]("T^('M](BYF;W)M870H<W1R*&ME>2DL('-T<BAI=&5M*2D*("`@(')E
1='5R;B!F;VQL;W=?<V5T<PHH
`
end
SHAR_EOF
  (set 20 18 10 19 16 37 44 'tools.py'
   eval "${shar_touch}") && \
  chmod 0664 'tools.py'
if test $? -ne 0
then ${echo} "restore of tools.py failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'tools.py': 'MD5 check failed'
       ) << \SHAR_EOF
600200372821f4b1cecf00e4a66895e2  tools.py
SHAR_EOF

else
test `LC_ALL=C wc -c < 'tools.py'` -ne 3977 && \
  ${echo} "restoration warning:  size of 'tools.py' is not 3977"
  fi
fi
# ============= grammar ==============
if test -n "${keep_file}" && test -f 'grammar'
then
${echo} "x - SKIPPING grammar (file already exists)"

else
${echo} "x - extracting grammar (text)"
  sed 's/^X//' << 'SHAR_EOF' > 'grammar' &&
Program_declaration     -> declaration_list
declaration_list        -> declaration declaration_list'
declaration_list'       -> declaration declaration_list' | @
declaration             -> type_specifier ID declaration'
declaration'            -> var_declaration' | ( params ) compound_statement
var_declaration         -> type_specifier ID var_declaration'
var_declaration'        -> ; | [ NUM ] ;
type_specifier          -> int | float | void
params                  -> void params' | int ID param' param_list' | float ID param' param_list'
params'                 -> ID param' param_list' | @
param_list              -> param param_list'
param_list'             -> , param param_list' | @
param                   -> type_specifier ID param'
param'                  -> [ ] | @
compound_statement      -> { local_declarations' statement_list' }
local_declarations'     -> var_declaration local_declarations' | @
statement_list'         -> statement statement_list' | @
statement               -> expression_statement | compound_statement | selection_statement | iteration_statement | return_statement
expression_statement    -> expression ; | ;
selection_statement     -> if ( expression ) statement selection_statement'
selection_statement'    -> else statement | @
iteration_statement     -> while ( expression ) statement
return_statement        -> return return_statement'
return_statement'       -> expression ; | ;
expression              -> ID expression' | ( expression ) term' additive_expression' simple_expression' | NUM term' additive_expression' simple_expression'
expression'             -> var' expression'' | ( args ) term' additive_expression' simple_expression' | @
expression''            -> = expression | term' additive_expression' simple_expression' | @
var                     -> ID var'
var'                    -> [ expression ] | @
simple_expression       -> additive_expression simple_expression'
simple_expression'      -> relational_operator additive_expression | @
relational_operator     -> <= | < | > | >= | == | !=
additive_expression     -> term additive_expression'
additive_expression'    -> additive_operator term additive_expression' | @
additive_operator       -> + | -
term                    -> factor term'
term'                   -> multiplicative_operator factor term' | @
multiplicative_operator -> * | /
factor                  -> ( expression ) | NUM | ID factor'
factor'                 -> ( args ) | [ expression ] | @
args                    -> argument_list | @
argument_list           -> expression argument_list'
argument_list'          -> , expression argument_list' | @
SHAR_EOF
  (set 20 18 10 19 16 36 30 'grammar'
   eval "${shar_touch}") && \
  chmod 0644 'grammar'
if test $? -ne 0
then ${echo} "restore of grammar failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'grammar': 'MD5 check failed'
       ) << \SHAR_EOF
b7d3e2d2c0be2513546598902495aadc  grammar
SHAR_EOF

else
test `LC_ALL=C wc -c < 'grammar'` -ne 2625 && \
  ${echo} "restoration warning:  size of 'grammar' is not 2625"
  fi
fi
# ============= p1.py ==============
if test -n "${keep_file}" && test -f 'p1.py'
then
${echo} "x - SKIPPING p1.py (file already exists)"

else
${echo} "x - extracting p1.py (text)"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 p1.py
M(B(B"E1H:7,@<')O9W)A;2!P97)F;W)M<R!T:&4@9G5N8W1I;VYS(&]F(&$@
M<V-A;FYE<B!F;W(@82!#+2!C;VUP:6QE<BX*36]D:69I960@9F]R('5S92!B
M>2!P87)S97(N"D%U=&AO<CH@2F]S97!H($%L;&5N"D1A=&4Z(#DO-2\Q.`HB
M(B(*9G)O;2!R92!I;7!O<G0@8V]M<&EL92P@;6%T8V@L(%,*"E-934)/3"`@
M(#T@)U-Y;6)O;"<*2T595T]21"`@/2`G2V5Y=V]R9"<*(TE.5"`@("`@(#T@
M)TEN="<*(T9,3T%4("`@(#T@)T9L;V%T)PI.54T@("`@("`]("=.54TG"DE$
M("`@("`@(#T@)TE$)PI%4E)/4B`@("`]("=%<G)O<B<*(T524D]2("`@(#T@
M)UQX,6);,3LS-SLT,6TG("L@)T524D]2)R`K("=<>#%B6S!M)R`C($1E8G5G
M(&AE;'`Z($5R<F]R<R!A<'!E87(@<F5D"DE.0T]-345.5"`]("=)3D-/34U%
M3E0G"D]55$-/34U%3E0@/2`G3U540T]-345.5"<*"B,@5&]K96X@9&5F:6YI
M=&EO;G,@*&-O;6UE;G1?9&5P=&@@/3T@,"D@5$]$3R!S:6UP;&EF>2`F(&]P
M=&EM:7IE(')E9V5X<PIT;VME;E]D969S(#T@6PH@("`@*&-O;7!I;&4H<B=<
M<RLG*2P@("`@("`@("`@("`@("`@("`@($YO;F4I+"`@("`@("`C(&UA=&-H
M97,@=VAI=&5S<&%C90H@("`@*&-O;7!I;&4H<B<O7"HG*2P@("`@("`@("`@
M("`@("`@("`@($E.0T]-345.5"DL("`C('-T87)T(&]F(&UL+6-O;6UE;G0*
M("`@("AC;VUP:6QE*'(G+R];7EQN72HG*2P@("`@("`@("`@("`@("!.;VYE
M*2P@("`@("`@(R!S:6YG;&4@;&EN92!C;VUM96YT"B`@("`H8V]M<&EL92AR
M)SP]?#X]?#T]?"$])RDL("`@("`@("`@("`@4UE-0D],*2P@("`@(",@9&]U
M8FQE('-Y;6)O;',*("`@("AC;VUP:6QE*'(G6RP[7"TK/#X]*B]=)RDL("`@
M("`@("`@("!364U"3TPI+"`@("`@(R!S:6YG;&4@<WEM8F]L<PH@("`@*&-O
M;7!I;&4H<B=;72@I6WM]72<I+"`@("`@("`@("`@("`@(%-934)/3"DL("`@
M("`C(&5N8VQO<VEN9R!S>6UB;VQS"@H@("`@(R!M871C:"!I;G9A;&ED(&EN
M=',*("`@("AC;VUP:6QE*'(G6S`M.5TK6V$M9&8M>D$M1$8M6EU;+C`M.6$M
M>D$M6ETJ)RDL("!%4E)/4BDL"@H@("`@(R!M871C:"!I;G9A;&ED($E$<PH@
M("`@*&-O;7!I;&4H<B=;82UZ02U:72M;+C`M.5U;+C`M.6$M>D$M6ETJ)RDL
M("`@("`@($524D]2*2P*"B`@("`C(&UA=&-H('9A;&ED($E$<PH@("`@*&-O
M;7!I;&4H<B=;82UZ02U:72LG*2P@("`@("`@("`@("`@($E$*2P*"B`@("`C
M(&UA=&-H('9A;&ED(&EN=',*("`@("AC;VUP:6QE*'(G*#\\(5M<9"Y=*5LP
M+3E=*R@_(5M<9"Y%95TI)RDL($Y532DL"@H@("`@(R!M871C:"!I;G9A;&ED
M(&9L;V%T<PH@("`@*&-O;7!I;&4H<B<H/SPA6V$M>D$M6ETI7&0J*"A<+EQD
M*BD_?%PN7&0K*5ME15U;+2M=/UQD*EMA+7I!+5I<+EU;82UZ02U:,"TY7"Y=
M*B<I+"!%4E)/4BDL(",@26YV86QI9"!38VEE;G1I9FEC"B`@("`H8V]M<&EL
M92AR)R@_/"%;82UZ02U:72DH7&0J7"Y<9"HI6V$M9&8M>D$M1$8M6EPN75MA
M+7I!+5HP+3E<+ETJ)RDL($524D]2*2P@(R!);G9A;&ED($9L;V%T"@H@("`@
M(R!M871C:"!V86QI9"!F;&]A=',*("`@("AC;VUP:6QE*'(G*#\\(5MA+7I!
M+5I=*5QD*BA<+EQD*RD_*%ME15U;+2M=/UQD*RDG*2P@3E5-*2P*("`@("AC
M;VUP:6QE*'(G*#\\(5MA+7I!+5I=*2A<9"I<+EQD*RDH/R%;945=*2<I+"!.
M54TI+`H@("`@"B`@("`C(&UA=&-H(&EN=F%L:60@8VAA<F%C=&5R(&%N9"!A
M;GET:&EN9R!A='1A8VAE9"!U;G1I;"!W:&ET97-P86-E(&]R('-Y;6)O;`H@
M("`@*&-O;7!I;&4H<B<N6UY=6R@I>WTK7"T]/#X]*B\[+%QS72HG+"!3*2P@
M("`@("`@("!%4E)/4BE="@HC($-O;6UE;G0@9&5F:6YI=&EO;G,@*&-O;6UE
M;G1?9&5P=&@@/B`P*0IC;VUM96YT7V1E9G,@/2!;"B`@("`H8V]M<&EL92AR
M)R]<*B<I+"`@("`@("`@("`@("`@("`@("`@24Y#3TU-14Y4*2P*("`@("AC
M;VUP:6QE*'(G7"HO)RDL("`@("`@("`@("`@("`@("`@("!/551#3TU-14Y4
M*2P*("`@("AC;VUP:6QE*'(G+B<L(%,I+"`@("`@("`@("`@("`@("!.;VYE
M*5T@(",@:6=N;W)E(&YO;F-O;6UE;G1S('=I=&AI;B!M;"UC;VUM96YT"@IK
M97EW;W)D<R`]('-E="A;)V5L<V4G+"`G:68G+"`G:6YT)RP@)V9L;V%T)RP@
M)W)E='5R;B<L("=V;VED)RP@)W=H:6QE)UTI(",@<'ET:&]N,BXV+C8@8V]M
M<&%T:6)L90H*"F1E9B!P,2AF:6QE;F%M92DZ"B`@("!T;VME;G,@/2!;70H@
M("`@;&EN95]T;VME;G,@/2!;70H@("`@8V]M;65N=%]D97!T:"`](#`*("`@
M('=I=&@@;W!E;BAF:6QE;F%M92P@)W(G*2!A<R!F.@H@("`@("`@(&9O<B!L
M:6YE(&EN(&8Z"B`@("`@("`@("`@(&QI;F4@/2!L:6YE+G-T<FEP*"D*("`@
M("`@("`@("`@(W!R:6YT("=)3E!55#H@)R`K(&QI;F4*("`@("`@("`@("`@
M:2`](#`*("`@("`@("`@("`@=VAI;&4@:2`\(&QE;BAL:6YE*3H*("`@("`@
M("`@("`@("`@(&UA=&-H(#T@3F]N90H@("`@("`@("`@("`@("`@9&5F<R`]
M('1O:V5N7V1E9G,@:68@8V]M;65N=%]D97!T:"`]/2`P(&5L<V4@8V]M;65N
M=%]D969S"B`@("`@("`@("`@("`@("!F;W(@9&5F:6YI=&EO;B!I;B!D969S
M.@H@("`@("`@("`@("`@("`@("`@(')E9V5X+"!L86)E;"`](&1E9FEN:71I
M;VX*("`@("`@("`@("`@("`@("`@("!M871C:"`](')E9V5X+FUA=&-H*&QI
M;F4L(&DI"B`@("`@("`@("`@("`@("`@("`@:68@;6%T8V@Z"B`@("`@("`@
M("`@("`@("`@("`@("`@('1E>'0@/2!M871C:"YG<F]U<"@P*0H@("`@("`@
M("`@("`@("`@("`@("`@("!I9B!L86)E;#H*("`@("`@("`@("`@("`@("`@
M("`@("`@("`@(&EF(&QA8F5L(#T]($E.0T]-345.5#H@8V]M;65N=%]D97!T
M:"`K/2`Q"B`@("`@("`@("`@("`@("`@("`@("`@("`@("!E;&EF(&QA8F5L
M(#T]($]55$-/34U%3E0Z(&-O;6UE;G1?9&5P=&@@+3T@,0H@("`@("`@("`@
M("`@("`@("`@("`@("`@("`@96QS93H@;&EN95]T;VME;G,N87!P96YD*'1E
M>'0@:68@=&5X="!I;B!K97EW;W)D<R!O<B!L86)E;"`]/2!364U"3TP@96QS
M92!L86)E;"D*("`@("`@("`@("`@("`@("`@("`@("`@8G)E86L*("`@("`@
M("`@("`@("`@(&D@/2!M871C:"YE;F0H,"D*("`@("`@("`@("`@(V9O<B!T
M;VME;B!I;B!L:6YE7W1O:V5N<SH@<')I;G0@=&]K96X*("`@("`@("`@("`@
M=&]K96YS+F5X=&5N9"AL:6YE7W1O:V5N<RD*("`@("`@("`@("`@9&5L(&QI
M;F5?=&]K96YS6SI="B`@("!T;VME;G,N87!P96YD*"<D)RD@(R!P<F5P(&%S
M('-T86-K(&9O<B!P87)S:6YG"B`@("!T;VME;G,N<F5V97)S92@I"B`@("!R
,971U<FX@=&]K96YS
`
end
SHAR_EOF
  (set 20 18 10 19 16 41 32 'p1.py'
   eval "${shar_touch}") && \
  chmod 0644 'p1.py'
if test $? -ne 0
then ${echo} "restore of p1.py failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'p1.py': 'MD5 check failed'
       ) << \SHAR_EOF
edb429d75ed4522cb13777f6ecb8e963  p1.py
SHAR_EOF

else
test `LC_ALL=C wc -c < 'p1.py'` -ne 3297 && \
  ${echo} "restoration warning:  size of 'p1.py' is not 3297"
  fi
fi
# ============= p2.py ==============
if test -n "${keep_file}" && test -f 'p2.py'
then
${echo} "x - SKIPPING p2.py (file already exists)"

else
${echo} "x - extracting p2.py (text)"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 p2.py
M(B(B"E1H:7,@<')O9W)A;2P@<#(N<'DL('!E<F9O<FUS('1H92!F=6YC=&EO
M;G,@;V8@86X@3$PH,2D@<&%R<V5R+B!)="!U<V5S"F$@<V-A;FYE<BP@<#$N
M<'DL('1O(&=A=&AE<B!T;VME;G,L(&QO861S(&$@9W)A;6UA<BP@;&]A9',@
M9FER<W0@<V5T<RP*8V]M<'5T97,@9F]L;&]W('-E=',L(&%N9"!R971U<FYS
M('1H92!R97-U;'0@;V8@82!P87)S90IW:71H('1H:7,@8V]N=&5X="X*"D)Y
M.B!*;W-E<&@@06QL96X*1&%T93H@,3`O,3DO,3@*(B(B"F9R;VT@<#$@:6UP
M;W)T('`Q(&%S('-C86X*9G)O;2!T;V]L<R!I;7!O<G0@;&]A9%]F:7)S=',L
M(&QO861?9W)A;6UA<BP@9FEN9%]F;VQL;W=S"F9R;VT@<&%R<V4@:6UP;W)T
M('!A<G-E"F9R;VT@<WES(&EM<&]R="!A<F=V"@II9B!?7VYA;65?7R`]/2`B
M7U]M86EN7U\B.@H*("`@(",@=7-E(%`Q('-C86YN97(@=&\@<V-A;B!S;W5R
M8V4@9FEL92!F;W(@=&]K96YS(&%N9"!G970@=&AE('1O:V5N('-T86-K"B`@
M("!T;VME;G,@/2!S8V%N*&%R9W9;,5TI"@H@("`@(R!L;V%D(&=R86UM87(@
M86YD('-O;64@=7-E9G5L('-E=',*("`@(&=R86UM87(L('1E<FUI;F%L<RP@
M;F]N=&5R;6EN86QS+"!S=&%R="`](&QO861?9W)A;6UA<B@B9W)A;6UA<B(I
M"@H@("`@(R!L;V%D(&9I<G-T('-E=',*("`@(&9I<G-T7W-E=',@/2!L;V%D
M7V9I<G-T<R@B9FER<W1?<V5T<R(I"@H@("`@(R!F:6YD('1H92!F;VQL;W<@
M<V5T<R!U<VEN9R!W:&%T('=E(&AA=F4*("`@(&9O;&QO=U]S971S(#T@9FEN
M9%]F;VQL;W=S*&=R86UM87(L(&YO;G1E<FUI;F%L<RP@=&5R;6EN86QS+"!F
M:7)S=%]S971S+"!S=&%R="D*"B`@("`C(&9I;F%L;'DL('!A<G-E('1H92!T
M;VME;G,*("`@(&%C8V5P="`]('!A<G-E*'1O:V5N<RP@9W)A;6UA<BP@9FER
M<W1?<V5T<RP@9F]L;&]W7W-E=',L('1E<FUI;F%L<RP@;F]N=&5R;6EN86QS
M+"!S=&%R="D*"B`@("`C(')E<W5L="!O9B!P87)S90H@("`@<')I;G0@(D%#
?0T505"(@:68@86-C97!T(&5L<V4@(E)%2D5#5"(@"@H@
`
end
SHAR_EOF
  (set 20 18 10 19 16 58 12 'p2.py'
   eval "${shar_touch}") && \
  chmod 0664 'p2.py'
if test $? -ne 0
then ${echo} "restore of p2.py failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'p2.py': 'MD5 check failed'
       ) << \SHAR_EOF
74c55518e8f016a0cefca036fe4d63ab  p2.py
SHAR_EOF

else
test `LC_ALL=C wc -c < 'p2.py'` -ne 1021 && \
  ${echo} "restoration warning:  size of 'p2.py' is not 1021"
  fi
fi
# ============= testfiles ==============
if test -n "${keep_file}" && test -f 'testfiles'
then
${echo} "x - SKIPPING testfiles (file already exists)"

else
${echo} "x - extracting testfiles (text)"
  sed 's/^X//' << 'SHAR_EOF' > 'testfiles' &&
int main(void){
X    {{{}}{int x;}}
X    {x(x);}
X    if (1) return x[1];
X    if (null) {
X        x = x; 1 + 2;
X        x + 1 + 2 / 3;
X    } else return 0;
X    while (0 <= x[2])
X        print(hello(world(x,x,z-z/z), x));
}
//-------------------------------------------------
/*
int gcd(int u, int v){
X    if (v == 0) return u;
X    else return gcd(v,u-u/v*v);
X    /* u-u/v*v == u mod v */
}
void main(void){
X    int x; int y;
X    x = input(); y = input();
X    output(gcd(x,y));
}
*/
//------------------------------------------------
/*
int x[10];
int minloc ( int a[], int low, int high ){
X    int i; int x; int k;
X    k = low;
X    x = a[low];
X    i = low + 1;
X    while ( i < high ){
X        if (a[i] < x){
X            x = a[i];
X            k = i;
X        }
X        i = i + 1;
X    }
X    return k;
}
X
void sort( int a[], int low, int high){
X    int i; int k;
X    i = low;
X    while ( i < high -1){
X        int t;
X        k = minloc(a,i,high);
X        t = a[k];
X        a[k] = a[i];
X        a[i] = t;
X        i = i + 1;
X    }
}
X
void main(void){
X    int i;
X    i = 0;
X    while (i < 10){
X        x[i] = input();
X        i = i + 1;
X    }
X    sort(x, 0, 10);
X    i = 0;
X    while (i < 10){
X        output(x[i]);
X        i = i + 1;
X    }
}
*/
X
SHAR_EOF
  (set 20 18 10 19 16 43 30 'testfiles'
   eval "${shar_touch}") && \
  chmod 0664 'testfiles'
if test $? -ne 0
then ${echo} "restore of testfiles failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'testfiles': 'MD5 check failed'
       ) << \SHAR_EOF
8895d72b19270ce584e7f781a0c6af29  testfiles
SHAR_EOF

else
test `LC_ALL=C wc -c < 'testfiles'` -ne 1237 && \
  ${echo} "restoration warning:  size of 'testfiles' is not 1237"
  fi
fi
# ============= typescript ==============
if test -n "${keep_file}" && test -f 'typescript'
then
${echo} "x - SKIPPING typescript (file already exists)"

else
${echo} "x - extracting typescript (text)"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 typescript
M4V-R:7!T('-T87)T960@;VX@,C`Q."TQ,"TQ.2`Q-CHT-CHU,"TP-#`P"AM=
M,#MJ;W-E<&A`;7-I.B!^+T1E<VMT;W`O0T]0-#8R,"!#;VUP:6QE<G,O4')O
M:F5C=#('&ULP,3LS,FUJ;W-E<&A`;7-I&ULP,&TZ&ULP,3LS-&U^+T1E<VMT
M;W`O0T]0-#8R,"!#;VUP:6QE<G,O4')O:F5C=#(;6S`P;20@8F%S:"!P,B!T
M97-T9FEL97,-"D%#0T505`T*&UTP.VIO<V5P:$!M<VDZ('XO1&5S:W1O<"]#
M3U`T-C(P($-O;7!I;&5R<R]0<F]J96-T,@<;6S`Q.S,R;6IO<V5P:$!M<VD;
M6S`P;3H;6S`Q.S,T;7XO1&5S:W1O<"]#3U`T-C(P($-O;7!I;&5R<R]0<F]J
M96-T,AM;,#!M)"!E>&ET#0IE>&ET#0H*4V-R:7!T(&1O;F4@;VX@,C`Q."TQ
3,"TQ.2`Q-CHT-SHP-2TP-#`P"FET
`
end
SHAR_EOF
  (set 20 18 10 19 16 47 05 'typescript'
   eval "${shar_touch}") && \
  chmod 0644 'typescript'
if test $? -ne 0
then ${echo} "restore of typescript failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'typescript': 'MD5 check failed'
       ) << \SHAR_EOF
9fc76bc773ae7a34e43b570df2cfeb97  typescript
SHAR_EOF

else
test `LC_ALL=C wc -c < 'typescript'` -ne 379 && \
  ${echo} "restoration warning:  size of 'typescript' is not 379"
  fi
fi
# ============= first_sets ==============
if test -n "${keep_file}" && test -f 'first_sets'
then
${echo} "x - SKIPPING first_sets (file already exists)"

else
${echo} "x - extracting first_sets (text)"
  sed 's/^X//' << 'SHAR_EOF' > 'first_sets' &&
Program_declaration     *{ int float void 
declaration_list        *{ int float void 
declaration_list'       *{ int float void @ 
declaration             *{ int float void 
declaration'            *{ ( ; [
var_declaration         *{ int float void 
var_declaration'        *{ ; [ 
type_specifier          *{ int float void 
params                  *{ int float void 
params'                 *{ ID @
param_list              *{ int float void 
param_list'             *{ , @ 
param                   *{ int float void 
param'                  *{ [ @ 
compound_statement      *{ { 
local_declarations      *{ int float void @ 
local_declarations'     *{ int float void @ 
statement_list          *{ ; ID ( NUM { if while return @ 
statement_list'         *{ ; ID ( NUM { if while return @ 
statement               *{ ; ID ( NUM { if while return 
expression_statement    *{ ; ID ( NUM 
expression_statement'   *{ ID ( NUM @ 
selection_statement     *{ if 
selection_statement'    *{ else @ 
iteration_statement     *{ while 
return_statement        *{ return 
return_statement'       *{ ; ID ( NUM 
return_statement''      *{ ID ( NUM @ 
expression              *{ ID ( NUM 
expression'             *{ ( [ = * / + - <= < > >= == != @
expression''            *{ = * / + - <= < > >= == != @ 
var                     *{ ID 
var'                    *{ [ @ 
simple_expression       *{ ( ID NUM 
simple_expression'      *{ <= < > >= == !=  @ 
relational_operator     *{ <= < > >= == != 
additive_expression     *{ ( ID NUM 
additive_expression'    *{ + - @ 
additive_operator       *{ + - 
term                    *{ ( ID NUM 
term'                   *{ * / @ 
multiplicative_operator *{ * / 
factor                  *{ ( ID NUM 
factor'                 *{ ( [ @ 
call                    *{ ID 
args                    *{ ID NUM ( @ 
argument_list           *{ ID ( NUM 
argument_list'          *{ , @ 
SHAR_EOF
  (set 20 18 10 18 18 12 46 'first_sets'
   eval "${shar_touch}") && \
  chmod 0644 'first_sets'
if test $? -ne 0
then ${echo} "restore of first_sets failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'first_sets': 'MD5 check failed'
       ) << \SHAR_EOF
2043f7f04bae2c0e6fcc38d3dd56d39c  first_sets
SHAR_EOF

else
test `LC_ALL=C wc -c < 'first_sets'` -ne 1895 && \
  ${echo} "restoration warning:  size of 'first_sets' is not 1895"
  fi
fi
# ============= makefile ==============
if test -n "${keep_file}" && test -f 'makefile'
then
${echo} "x - SKIPPING makefile (file already exists)"

else
${echo} "x - extracting makefile (text)"
  sed 's/^X//' << 'SHAR_EOF' | uudecode &&
begin 600 makefile
M86QL.@H)0&5C:&\@(DYO(&UA:V5F:6QE(&YE8V5S<V%R>2X@4')O:F5C="!W
2<FET=&5N(&EN(%!Y=&AO;BXB
`
end
SHAR_EOF
  (set 20 18 09 03 16 19 31 'makefile'
   eval "${shar_touch}") && \
  chmod 0664 'makefile'
if test $? -ne 0
then ${echo} "restore of makefile failed"
fi
  if ${md5check}
  then (
       ${MD5SUM} -c >/dev/null 2>&1 || ${echo} 'makefile': 'MD5 check failed'
       ) << \SHAR_EOF
559757f712a4dcec261c6c2e742c095e  makefile
SHAR_EOF

else
test `LC_ALL=C wc -c < 'makefile'` -ne 63 && \
  ${echo} "restoration warning:  size of 'makefile' is not 63"
  fi
fi
if rm -fr ${lock_dir}
then ${echo} "x - removed lock directory ${lock_dir}."
else ${echo} "x - failed to remove lock directory ${lock_dir}."
     exit 1
fi
exit 0
